### ISSUE TITLE
reload api server

### ISSUE THREAD

**Issue by arhmnsh** [fullstackreact/food-lookup-demo#13]
Hi!
How can I reload(?) the server, every time I change server code? Like how it is done for the react app

**Comment by GramParallelo** [comment]
Use nodemon:
    
    "server": "nodemon --watch src --exec babel-node -- src/index.js"

**Comment by acco** [comment]
Hi @arhmnsh — yep, @GramParallelo suggests a great solution! Closing this, feel free to comment if you have any more questions

**Comment by arhmnsh** [comment]
Hi @GramParallelo,
Tried it doesn't work. My server doesn't even start. Are you sure about the `src/index.js` part?
I see that you're referencing the file inside the `client`. I guess we should `babel-node` the `server.js` file.

**Comment by acco** [comment]
Hi @arhmnsh -- you are correct! That shouldn't be `src/index.js`, it should be the `server.js`. Let me know if you get it to work
