### ISSUE TITLE
Browser doesn't open with latest react-sripts

### ISSUE THREAD

**Issue by CaryLandholt** [fullstackreact/food-lookup-demo#14]
Firstly, thank you for this project!

After upgrading to react-scripts >= 8.0 and executing `npm start`, the browser no longer launches automatically.  This happens with foreman as well as concurrently.

Any ideas?

Thanks much!

**Comment by acco** [comment]
Hi @CaryLandholt,

Thanks for reporting!

Looking at the [changelog](https://github.com/facebookincubator/create-react-app/releases), it would appear there's been a lot of activity around the browser launching in the last few days. Have you tried with `0.8.4` by chance?

**Comment by CaryLandholt** [comment]
Yeah, saw the same thing.  Tried 0.8.4 this morning.  Still doesn't work, unfortunately.

**Comment by acco** [comment]
@CaryLandholt Bah, thanks for checking. I'll try to look at it this week!

**Comment by CaryLandholt** [comment]
thanks much!

**Comment by CaryLandholt** [comment]
Closing due to https://github.com/facebookincubator/create-react-app/issues/1263 and https://github.com/facebookincubator/create-react-app/pull/1264

**Comment by acco** [comment]
Thanks for being on top of this, @CaryLandholt !
