### ISSUE TITLE
I'm not able to deploy to heroku?

### ISSUE THREAD

**Issue by lambbyrd** [fullstackreact/food-lookup-demo#18]
Sorry if this is the wrong place to ask this question...

I followed your tutorial, and have been pouring over all your files to see where I might have messed up. But for some reason,  I can't get it to work. It will only launch my server side but won't use the client/build to deploy static files.

I don't see what it is I'm doing wrong, It works great locally.

Also the logs on heroku haven't been much help.... not saying much. 

Here is my repo: https://github.com/codepressd/salut

Any insight would be much appreciated.

Chris

**Comment by Joe312341** [comment]
I can confirm that the app works on heroku, are you still having problems?

**Comment by lambbyrd** [comment]
Thanks for the reply!

No worries I was being an idiot and ignoring my build folder...

Sorry to waste your time..

Chris
