### ISSUE TITLE
Cannot serve any other .html files

### ISSUE THREAD

**Issue by swyxio** [fullstackreact/food-lookup-demo#19]
I am trying to extend this project to serve new files and am running into major issues. for example if I add this to routes/index.js:

```
app.route('/login')
.get(function (req, res) {
res.sendFile('./client/public/login.html', { root: __dirname });
});
```

the dirname is just completely wrong and nothing I can do helps (i've tried everything including adding path.resolve). Bottomline is it really doesnt look like this route is run on the server at all. this suspicion is further confirmed if I mess around with the '/' route:

```
app.route('/')
.get(function (req, res) {
res.sendFile(bipath.join(__dirname, '../public', 'THISCANBEANYRANDOMFILENAME.html'))
});
```

and the app still works fine because you configured webpack so that "All requests to `localhost:3000` will serve `client/index.html". How did you do that!

So really i have two questions here. Hope i made sense. I also logged this on SO: http://stackoverflow.com/questions/41859154/webpack-somehow-bypasses-express-routing-completely

**Comment by acco** [comment]
Hey @sw-yx !

In development, the server in the top-level directory (`server.js`) shouldn't serve any static files at all. We have Webpack handle that for us. So, if you put a file in `client/public` like this:

```
echo '<h1>Hi, @sw-yx!</h1>' > client/public/some-file.html
```

You'll be able to access it here:

```
localhost:3000/some-file.html
```

![](https://monosnap.com/file/iDURlpOob3qUUQOClU2DXMRnHTAhD5.png)

Let me know if you're instead talking about production (we have the server [serve static assets in production](https://github.com/fullstackreact/food-lookup-demo/blob/master/server.js#L13-L16))

**Comment by swyxio** [comment]
Hey Anthony, this is really really late but i wanted to thank you for your response. i made that comment when i was still a newbie dev and i understand things a lot better now. thanks for being helpful to newbies and i plan to do the same.

**Comment by acco** [comment]
@sw-yx Great to hear one year later you've made so much progress! Best of luck
