### ISSUE TITLE
after `npm run server` localhost:3001 only displays "Cannot Get /"

### ISSUE THREAD

**Issue by chris3jang** [fullstackreact/food-lookup-demo#20]
Hello, I am rather inexperienced with both react and fullstack.  I am following the blog post step by step, early on I get to the point of running `npm run server` and it does without error.

![screen shot 2017-03-06 at 11 38 14 pm](https://cloud.githubusercontent.com/assets/12735262/23642209/def2315a-02c6-11e7-8134-e14e80bfbfa6.png)

But when I open localhost:3001 in my browser, instead of seeing the server as shown in the images of the blog, I see:

![screen shot 2017-03-06 at 11 38 01 pm](https://cloud.githubusercontent.com/assets/12735262/23642181/bbe76194-02c6-11e7-98e5-d86b944dc701.png)

Before exiting the `npm run server` command, I called curl in a separate window and also got:

![screen shot 2017-03-06 at 11 38 36 pm](https://cloud.githubusercontent.com/assets/12735262/23642216/ec00949a-02c6-11e7-8565-c839c1889efe.png)

I'd like to point out that everything else went according to the blog's directions EXCEPT that neither `npm start` nor `npm run server` opened a browser tab on its own the way `npm start` does for create-react-app project.  i had to type localhost:3000 and localhost:3001 for runs of start and run server respectively, and only had an issue with 3001/run server.  

Any help troubleshooting would be much appreciated, again I'm rather inexperienced so if there's a better way to ask or any obvious resources I can be pointed towards, that would be helpful as well.  Thank you!

**Comment by acco** [comment]
Hi @chris3jang!

The React app runs on `localhost:3000`. You're looking at the API server which runs on `localhost:3001`.

The API server only serves one specific route. `/` is not one of them. You can see the one route it's registered to respond to here:

https://github.com/fullstackreact/food-lookup-demo/blob/master/server.js#L27

Therefore, typing that into your browser you get:

![](https://monosnap.com/file/iRjw6lODfiVWKC7NnT2lIEi9a8wHJ3.png)

It's expecting the query param `q`. Adding that we'll see a list of JSON results:

![](https://monosnap.com/file/FESfBR8xfutktk84zo9AqQTDry5PxO.png)

Not pretty, but good enough for React!

Running `npm run server` will only boot the API server. `npm start` will start both the React app and the API server. You will be able to find the React app at `localhost:3000` after everything boots.

If you'd like, it could be a good UX for future developers to see _something_ if they visit `localhost:3001/`. If you wanna open a PR, that would be appreciated :)

Closing the issue, feel free to open if you encounter further issues.

Best,
A
