### ISSUE TITLE
Production build without need for babel

### ISSUE THREAD

**Issue by datenreisender** [fullstackreact/food-lookup-demo#22]
The [description on deployment](https://github.com/fullstackreact/food-lookup-demo#deploying) mentions that in production `npm run server` should be run. 

But there is a downside to this: `npm run server` invokes `babel-node`. It would be nicer to have – like create-react-app – a production build that does not need `babel` anymore but can be run with plain Node.JS.

**Comment by datenreisender** [comment]
Then again, there is almost no need, to really use babel for the server at all: Just throw out the trailing comma in https://github.com/fullstackreact/food-lookup-demo/blob/master/server.js#L61 and you can remove the babel dependencies in https://github.com/fullstackreact/food-lookup-demo/blob/master/package.json and replace `babel-node` with `node`.

**Comment by acco** [comment]
Slept on this one but just implemented - Thanks, @datenreisender  !
