### ISSUE TITLE
Automatically restart on change code is gone

### ISSUE THREAD

**Issue by zarnihpyoe** [fullstackreact/food-lookup-demo#23]
Everything works fine except the automatically ​restarting server and client is not working anymore. Should use nodemon? If so how about client?

**Comment by acco** [comment]
Hi @zarniphyo 

By "automatically restarting" are you referring to restarting after code changes?

If so, the client should still work fine. The server never had this feature.

Let me know.

**Comment by acco** [comment]
Closing this one, feel free to re-open if you have a response to my previous question!
