### ISSUE TITLE
How is Heroku able to see the API without Bundling in build?

### ISSUE THREAD

**Issue by tobsbola** [fullstackreact/food-lookup-demo#24]
Can someone please explain how the server is being bundled up to the heroku end of things? Seeing that its only the build that's deployed

**Comment by acco** [comment]
Hey @tobsbola 

We actually deploy the whole repo, API included. Heroku boots our API/node.js server. And then, nestled inside `client/build` are the assets for our React app. The node server serves the React app (the `index.html`, js files, css, etc) when the browser loads the page. Then the React app communicates with the API server in response to user interaction.

Make sense?

**Comment by tobsbola** [comment]
Awesome!!!.

**Comment by acco** [comment]
💃  Re-open if you have more questions!
