### ISSUE TITLE
Unmet peer dependency for eslint-config-airbnb-base@11.2.0

### ISSUE THREAD

**Issue by reefloretto** [fullstackreact/food-lookup-demo#26]
It looks like `eslint@^3.19.0` is a required peer dependency for the package `eslint-config-airbnb-base@11.2.0`. Is it appropriate to change the top-level `package.json` file to include `"eslint": "^3.19.0"` instead of `"eslint": "3.15.0"`?

**Comment by acco** [comment]
Indeed, thanks again @reefloretto !
