### ISSUE TITLE
HTTPS support example (with Heroku)

### ISSUE THREAD

**Issue by horak** [fullstackreact/food-lookup-demo#30]
I'm not sure how much legwork an https example would require, but it would go much appreciated. 

Given that I'm using Heroku's new Automated Certificate Management, what specifically would need to change within the provided `server.js` and the `Client.js`'s fetch calls to make this work?

While in production, I'm using this within `server.js` to re-route everything through https.

```Javascript
  app.use((req, res, next) => {
    if (req.header['x-forwarded-proto'] !== 'https')
      res.redirect(`https://${req.header('host')}${req.url}`)
    else
      next()
  })
```

Though, this produces CORS problems.

One issue I foresee here is that the documentation indicates:
> The API URL in development matches that in production.

Which, since I do not need to setup a ssl certificate for local development, indicates I might need to do something like this:

```Javascript
const apiBaseUrl = process.env.NODE_ENV === 'development' ? 'localhost:3001' : '?'
```

Though I'm not sure how to make this all fit together with fullstackreact's existing setup.

Thanks

**Comment by sfthurber** [comment]
i have an example that does work on https deployed on heroku. it serves the React build from the document root with the mongodb tier on mlab: 
https://github.com/sfthurber/MERNstack

i have also run it https on red hat's openshift with both the express and mongo in containers in a single deployment on openshift
