### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by AMichaelSuess** [fullstackreact/food-lookup-demo#33]
Dear author(s),

first of all, thanks for the great tutorial and repo, very appreciated! What I am missing is a LICENSE, though. As it is clearly meant to be reused, something like an MIT-license for the whole repository would be great, as otherwise nobody is able to use your work in their own projects. Thanks and once again, great work!

**Comment by drouillard** [comment]
Agreed.

Possible to get MIT or Apache 2.0 License added?

**Comment by drouillard** [comment]
@acco if this is not meant to be an MIT style project that would be good to know in terms of what acknowledgement/restrictions you would require.

**Comment by auser** [comment]
I've added the MIT license. Thanks for asking!
