### ISSUE TITLE
readme info didn't work for me

### ISSUE THREAD

**Issue by byumark** [fullstackreact/food-lookup-demo#38]
This didn't work for me:
git clone git@github.com:fullstackreact/food-lookup-demo.git

This did work for me:
git clone https://github.com/fullstackreact/food-lookup-demo.git

**Comment by drouillard** [comment]
You need to have ssh keys setup for the first one to work

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
