### ISSUE TITLE
Proxy don't work after production build

### ISSUE THREAD

**Issue by AdamDomagalsky** [fullstackreact/food-lookup-demo#40]
I've cloned the repo, everything is working fine, but after runing _npm run build_ and running a prod version of clinet - it looks like we are loosing connection between client and API.

Any ideas how to fix that?

**Comment by lomoY** [comment]
does it work well in your development environment? I follow the suggestion in this repo but it not works for me.

Then I set the below code in my server.js:
```
app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
  });
```

**Comment by auser** [comment]
Yes, if you run the production build using the following code, the server will serve the production version of the application:

```bash
NODE_ENV=production npm run start
```
This will work only after you `build` the client:

```bash
(cd client && npm run build)
```
