### ISSUE TITLE
Proxy error: Could not proxy request

### ISSUE THREAD

**Issue by borisyordanov** [fullstackreact/food-lookup-demo#48]
I saw [this](https://github.com/fullstackreact/food-lookup-demo/issues/40) issue already, but as i don't see how building the client might cause the error i decided to create a new issue.

The only modifications i've made to your structure is i've put the server files in "/server" and not in the root of the app.

**The problem**
When i run `npm start` and the server and client starts, when i make any request to the server i get the error:
```
[1] Proxy error: Could not proxy request /api/sendEmail from localhost:3000 to http://localhost:3001/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

Any idea what is causing this and how i can fix it?

FYI the issue happens only when i run the server locally. On the deployed version at Heroku everything works.

**Server package.json**
```
{
	"name": "lookup-server",
	"version": "0.0.1",
	"private": true,
	"dependencies": {
		"babel-core": "6.14.0",
		"body-parser": "^1.18.2",
		"cors": "^2.8.4",
		"express": "4.13.3",
		"fs": "0.0.2",
		"node-schedule": "^1.3.0",
		"nodemailer": "^4.4.2",
		"sql.js": "0.3.2",
		"stripe": "^5.4.0"
	},
	"scripts": {
		"start": "concurrently \"npm run server\" \"npm run client\"",
		"server": "node server/server.js",
		"client": "node start-client.js",
		"dev": "echo \"This command has been deprecated. Use 'npm start'\" && exit 1",
		"lint": "eslint ."
	},
	"devDependencies": {
	}
}
```
**Client package.json**
```
{
	"name": "enjoy-copenhagen",
	"version": "0.1.0",
	"private": true,
	"proxy": "http://localhost:3001/",
	"dependencies": {
	},
	"scripts": {
		"build-css": "node-sass-chokidar src/ -o src/",
		"watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
		"start-js": "react-scripts start",
		"start": "npm-run-all -p watch-css start-js",
		"build-js": "react-scripts build",
		"build": "npm-run-all build-css build-js",
		"test": "react-scripts test --env=jsdom",
		"eject": "react-scripts eject"
	},
	"devDependencies": {

	}
}

```

**Comment by borisyordanov** [comment]
It appears as though this bug was happening was due to syntax errors in my server-side js. Once they were resolved the api started working again.

**Comment by mikeheiser9** [comment]
what were the syntax errors?

**Comment by borisyordanov** [comment]
@mikeheiser9 Just random syntax errors. Trying to use a variable that doesn't exist or whatever. It had nothing to do with deployment

**Comment by ariel-frischer** [comment]
Just for the record I had the same proxy error and although my application was building without any errors, running `yarn start` or `npm start` for my project showed an error from mongoose package, when that error was resolved the proxy error also went away. Make sure to scroll all the way up before any compilation warnings to see if you actually have an error as well!
