### ISSUE TITLE
SQL injection?

### ISSUE THREAD

**Issue by tomjakubowski** [fullstackreact/food-lookup-demo#6]
Sorry, just a drive-by jackass here :-)

Isn't there a SQL injection flaw here? https://github.com/fullstackreact/food-lookup-demo/blob/master/server.js#L32

```
  const r = db.exec(`
    select ${COLUMNS.join(', ')} from entries
    where description like '%${param}%'
    limit 100
  `);
```

That will interpolate the variable `param`, which comes from the query string, directly in the SQL string.

**Comment by acco** [comment]
Hey @tomjakubowski — thanks for your patience, missed the notification on this one.

You are right 😫 

I just spent a little more time than I should have trying to get [sql.js](https://github.com/kripken/sql.js) to behave but I must be doing something wrong. `prepare()` appears to be the method we seek, but even after sorting its usage I keep getting empty result sets. So... went with this instead ...

https://github.com/fullstackreact/food-lookup-demo/commit/543c6779ccfd6f7985596619537249ebc5664ec5

:) Yours,
A
